// Every Pawpado feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 42 feature routes of the Pawpado API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Delete account (POST /api/v1/account/delete) */
  accountDelete(input: { "confirm": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/delete`, query, all);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Delete an api key (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** The workspace's audit trail, newest first, cursor-paginated. (GET /api/v1/audit-log) */
  auditLogList(input?: { "cursor"?: string; "limit"?: number; "action"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["action"] = all["action"]; delete all["action"];
    return this.call("GET", `/api/v1/audit-log`, query, undefined);
  }

  /** Grow the workspace's disk to storageGb (owner/admin). (POST /api/v1/billing/storage) */
  billingCreateStorage(input: { "storageGb": number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/storage`, query, all);
  }

  /** The storage sizes on offer (presets, min, max GB). (GET /api/v1/billing/storage) */
  billingStorage(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/storage`, {}, undefined);
  }

  /** Start a checkout that tops up the workspace's wallet (amountIdr, or amountUsdCents for PayPal/USD). (POST /api/v1/credits/topup) */
  creditsCreateTopup(input?: { "amountIdr"?: number; "amountUsdCents"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/credits/topup`, query, all);
  }

  /** The workspace's wallet and its 25 latest transactions. (GET /api/v1/credits/me) */
  creditsMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/credits/me`, {}, undefined);
  }

  /** The top-up amounts on offer (IDR presets and range; USD cents). (GET /api/v1/credits/topup) */
  creditsTopup(): Promise<unknown> {
    return this.call("GET", `/api/v1/credits/topup`, {}, undefined);
  }

  /** The optional post-session survey. (POST /api/v1/feedback) */
  feedbackCreate(input: { "sessionId": string; "rating": number; "experience"?: string; "gamesPlayed"?: string; "gameWanted"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/feedback`, query, all);
  }

  /** Has this session been answered yet? (GET /api/v1/feedback) */
  feedbackList(input: { "sessionId": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["sessionId"] = all["sessionId"]; delete all["sessionId"];
    return this.call("GET", `/api/v1/feedback`, query, undefined);
  }

  /** Change the streaming quality, the concurrent-stream (local-multiplayer) count, the product tier, and/or the baked image a Custom machine is built from, for the workspace member. (POST /api/v1/machines/config) */
  machinesConfig(input?: { "streamingQuality"?: string; "concurrentStreams"?: number; "machineTier"?: string; "machineImage"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/machines/config`, query, all);
  }

  /** Persist the machine configuration chosen in the "build your machine" form. (POST /api/v1/machines) */
  machinesCreate(input: { "instanceType": string; "streamingQuality": string; "storageGb": number; "region"?: string; "concurrentStreams"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/machines`, query, all);
  }

  /** Delete the workspace's one computer. (DELETE /api/v1/machines) */
  machinesDelete(): Promise<unknown> {
    return this.call("DELETE", `/api/v1/machines`, {}, undefined);
  }

  /** Change the machine's CPU & RAM tier (g5.xlarge ↔ g5.2xlarge ↔ g5.4xlarge) in place. (POST /api/v1/machines/resize) */
  machinesResize(input: { "instanceType": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/machines/resize`, query, all);
  }

  /** Record that the setup checklist was seen, for the signed-in person (or, with an API key, the person who made the key). (POST /api/v1/onboarding/acknowledge) */
  onboardingAcknowledge(): Promise<unknown> {
    return this.call("POST", `/api/v1/onboarding/acknowledge`, {}, undefined);
  }

  /** How to reach the workspace's running machine: its public address, tailnet address, RDP and Apollo credentials, client download links. (GET /api/v1/sessions/connect) */
  sessionsConnect(): Promise<unknown> {
    return this.call("GET", `/api/v1/sessions/connect`, {}, undefined);
  }

  /** Return the auth key the user pastes (or scans via QR) into the Tailscale app on their iPad/phone so the device joins our tailnet under tag:pawpado-user. (POST /api/v1/sessions/tailscale-key) */
  sessionsCreateTailscaleKey(): Promise<unknown> {
    return this.call("POST", `/api/v1/sessions/tailscale-key`, {}, undefined);
  }

  /** Pair a Moonlight client with the running machine: send the 4-digit PIN Moonlight shows. (POST /api/v1/sessions/pair) */
  sessionsPair(input: { "pin": string; "deviceName"?: string; "via"?: "desktop" | "mobile"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sessions/pair`, query, all);
  }

  /** The browser's view of the session state machine. (GET /api/v1/sessions/poll) */
  sessionsPoll(): Promise<unknown> {
    return this.call("GET", `/api/v1/sessions/poll`, {}, undefined);
  }

  /** Start session (POST /api/v1/sessions/start) */
  sessionsStart(): Promise<unknown> {
    return this.call("POST", `/api/v1/sessions/start`, {}, undefined);
  }

  /** Stop session (POST /api/v1/sessions/stop) */
  sessionsStop(input?: { "force"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/sessions/stop`, query, all);
  }

  /** Return the auth key the user pastes (or scans via QR) into the Tailscale app on their iPad/phone so the device joins our tailnet under tag:pawpado-user. (GET /api/v1/sessions/tailscale-key) */
  sessionsTailscaleKey(): Promise<unknown> {
    return this.call("GET", `/api/v1/sessions/tailscale-key`, {}, undefined);
  }

  /** Get settings client prefs (GET /api/v1/settings/client-prefs) */
  settingsClientPrefs(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings/client-prefs`, {}, undefined);
  }

  /** List settings (GET /api/v1/settings) */
  settingsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/settings`, {}, undefined);
  }

  /** Update settings (PATCH /api/v1/settings) */
  settingsUpdate(input?: { "idleAutoStopMinutes"?: number; "playMode"?: string; "launchOptions"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/settings`, query, all);
  }

  /** The 23 settings the stream URL cannot carry. (PATCH /api/v1/settings/client-prefs) */
  settingsUpdateClientPrefs(input: { "clientPrefs": Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/settings/client-prefs`, query, all);
  }

  /** Create a snapshot of the caller's machine. (POST /api/v1/snapshots) */
  snapshotsCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/snapshots`, query, all);
  }

  /** Delete the AWS EBS snapshot + the row. (DELETE /api/v1/snapshots/{id}) */
  snapshotsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/snapshots/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List this workspace's snapshots (newest first). (GET /api/v1/snapshots) */
  snapshotsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/snapshots`, {}, undefined);
  }

  /** Roll the caller's machine back to this snapshot. (POST /api/v1/snapshots/{id}/restore) */
  snapshotsRestore(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/snapshots/${encodeURIComponent(id)}/restore`, {}, undefined);
  }

  /** Live creation progress for one snapshot, workspace-scoped. (GET /api/v1/snapshots/{id}/status) */
  snapshotsStatus(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/snapshots/${encodeURIComponent(id)}/status`, {}, undefined);
  }

  /** What the Play grid renders. (GET /api/v1/stream/apps) */
  streamApps(): Promise<unknown> {
    return this.call("GET", `/api/v1/stream/apps`, {}, undefined);
  }

  /** Add a subscription: an https `url` (not a private, loopback or link-local address) and `events` — "*", event types from GET /api/v1/webhooks/event-types, or prefixes like "pawpado.session.*" (default  (POST /api/v1/webhooks) */
  webhooksCreate(input?: { "url"?: string; "events"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhooks`, query, all);
  }

  /** Remove a subscription (and its delivery log). (DELETE /api/v1/webhooks/{id}) */
  webhooksDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhooks/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** The delivery log, newest first: one row per event per subscription, with its status (pending, succeeded, failed), attempt count, next retry, the body sent (`payload`) and every attempt made (`attemptL (GET /api/v1/webhooks/deliveries) */
  webhooksDeliveries(input?: { "limit"?: number; "status"?: string; "cursor"?: string; "subscriptionId"?: string; "type"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["subscriptionId"] = all["subscriptionId"]; delete all["subscriptionId"];
    query["type"] = all["type"]; delete all["type"];
    return this.call("GET", `/api/v1/webhooks/deliveries`, query, undefined);
  }

  /** One more attempt now, at a failed delivery (or to send a succeeded one again). (POST /api/v1/webhooks/deliveries/{deliveryId}/retry) */
  webhooksDeliveriesRetry(deliveryId: string): Promise<unknown> {
    return this.call("POST", `/api/v1/webhooks/deliveries/${encodeURIComponent(deliveryId)}/retry`, {}, undefined);
  }

  /** Every event type Pawpado delivers, with what it means: what a subscription's `events` can name (besides "*" and prefixes such as "pawpado.session.*"). (GET /api/v1/webhooks/event-types) */
  webhooksEventTypes(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks/event-types`, {}, undefined);
  }

  /** One delivery, with every attempt made at it. (GET /api/v1/webhooks/deliveries/{deliveryId}) */
  webhooksGetDeliveries(deliveryId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks/deliveries/${encodeURIComponent(deliveryId)}`, {}, undefined);
  }

  /** The workspace's webhook subscriptions, each with its failure streak (consecutiveFailures, failingSince) and, when Pawpado switched it off for failing, disabledAt and disabledReason. (GET /api/v1/webhooks) */
  webhooksList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks`, {}, undefined);
  }

  /** Change a subscription: `url`, `events`, `active` (only the ones given). (PATCH /api/v1/webhooks/{id}) */
  webhooksUpdate(id: string, input?: { "url"?: string; "events"?: unknown; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhooks/${encodeURIComponent(id)}`, query, all);
  }
}
